work docker
Otus-DevOps-2022-02/ashfauihf_microservices pull request #1
Opened 2022-05-18 15:21 UTC by ashfauihf

2022-05-18 15:23 UTC, ashfauihf commented
Добрый день!
Можете уточнить в этой части тестов не будет? И как делать мерджи?

2022-05-20 08:47 UTC, mrgreyves requested changes
Здравствуйте!)
Тесты будут, их нужно так же перенести из предыдущего репозитория
Приключение на 2 минуты, точно не займет много времени =)

2022-05-20 08:52 UTC, ashfauihf commented
Можете подсказать что именно нужно перенести, я похоже что-то упустил в дз

2022-05-20 15:09 UTC, ashfauihf commented
Вы можете написать что конкретно нужно перенести с infra в microservices

2022-05-21 07:11 UTC, closed without merging