Docker 2
Otus-DevOps-2022-02/ashfauihf_microservices pull request #2
Opened 2022-05-21 07:12 UTC by ashfauihf

2022-05-21 11:18 UTC, mrgreyves requested changes
Здравствуйте!)
Оставил комментарий к файлу
ДЗ отправляю на доработку

2022-05-21 11:18 UTC, mrgreyves commented on docker-monolith/Dockerfile
> +FROM ubuntu:18.04
У вас образ из этого докерфайла собирается?
Кажется именно тут проблемы

2022-05-23 08:52 UTC, ashfauihf commented on docker-monolith/Dockerfile
> +FROM ubuntu:18.04
Образ собирается и к вебке доступ есть.
ubuntu                      18.04     c6ad7e71ba7d   3 weeks ago   63.2MB

2022-05-24 10:11 UTC, mrgreyves approved these changes
Здравствуйте!)
Апрув ^_^

2022-05-24 10:14 UTC, merged